name: Sync Master Tokens to Sites

on:
  push:
    paths:
      - "master/**"
    branches:
      - main

jobs:
  sync-master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy master tokens into each site
        run: |
          SITE_FOLDERS=$(ls -d */ | grep -v '^master/$' | grep -v '^.github/$')
          for folder in $SITE_FOLDERS; do
            mkdir -p "$folder/core"
            cp -r master/* "$folder/core/"
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync master tokens to all sites" || echo "No changes to commit"
          git push
